local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "Telescope find git files" })
vim.keymap.set("n", "<leader>/", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>ff", function()
	require("kelwan.telescope-config").project_files()
end, { desc = "Telescope find files" })
